version: '3.9'

networks:
  es-net:
    attachable: true

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.1
    ports:
    - 9200:9200
    - 9300:9300
    environment:
      discovery.type: 'single-node'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      xpack.security.enabled: 'false'
    volumes:
    - 'es-data:/usr/shared/elasticsearch/data'
    networks:
    - es-net
    deploy:
      replicas: 1
  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.1 
    ports:
    - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://es:9200
    networks:
    - es-net
    depends_on:
    - es
    deploy:
      replicas: 1
  fluentd:
    image: aolweny/fluentd-custom:latest
    environment:
      SERVICE_TAG: "service.*"
      ELASTICSEARCH_HOST: es
    deploy:
      replicas: 1
    networks:
      - es-net

volumes:
  es-data:
    driver: local
