version: '3.9'

networks:
  logging:
    attachable: true

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    ports:
    - 9200:9200
    - 9300:9300
    environment:
      discovery.type: 'single-node'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    volumes:
    - 'es-data:/usr/shared/elasticsearch/data'

volumes:
  es-data:
    driver: local
